//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DataExploration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Grams { get; set; }
        public Nullable<int> Percent { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
